Fix Pronto::Formatter::GithubPullRequestReviewFormatter error
Example error:

```
NoMethodError: undefined method `position' for nil:NilClass
from .../.gem/ruby/2.5.3/gems/pronto-0.10.0/lib/pronto/formatter/github_pull_request_review_formatter.rb:20:in `line_number'
```

This can happen in the context of this pronto-bundler audit gem since we
aren't necessarily altering the Gemfile.lock file within a PR at the
time of finding an issue in the Gemfile.lock file.

Since Pronto doesn't provide a way to supply custom formatters, our
best bet is to monkey patch the default
Pronto::Formatter::GithubPullRequestReviewFormatter with a method
that will perform the way we need it to.